### PR TITLE
cleanup test warning

### PR DESCRIPTION
**Pull request by dengliming**
closes [https://github.com/redis/jedis/issues/2479](https://github.com/redis/jedis/issues/2479)

### CODE REVIEW

**Comment by dengliming** [comment]
@sazzad16 @gkorland Can you take a look on this?

**Comment by sazzad16** [comment]
@dengliming What's the warning? Aren't the tests running okay?

**Comment by dengliming** [comment]
Not completely right. : )
```
[WARN ] 2021-03-23T01:42:39,330 [main]         r.c.j.ShardedJedisPool - Error while QUIT java.lang.ClassCastException: java.lang.Long cannot be cast to [B
	at redis.clients.jedis.Connection.getStatusCodeReply(Connection.java:265) ~[classes/:?]
	at redis.clients.jedis.BinaryJedis.quit(BinaryJedis.java:457) ~[classes/:?]
	at redis.clients.jedis.ShardedJedisPool$ShardedJedisFactory.destroyObject(ShardedJedisPool.java:84) [classes/:?]
	at org.apache.commons.pool2.PooledObjectFactory.destroyObject(PooledObjectFactory.java:126) [commons-pool2-2.9.0.jar:2.9.0]
	at org.apache.commons.pool2.impl.GenericObjectPool.destroy(GenericObjectPool.java:958) [commons-pool2-2.9.0.jar:2.9.0]
	at org.apache.commons.pool2.impl.GenericObjectPool.clear(GenericObjectPool.java:677) [commons-pool2-2.9.0.jar:2.9.0]
	at org.apache.commons.pool2.impl.GenericObjectPool.close(GenericObjectPool.java:721) [commons-pool2-2.9.0.jar:2.9.0]
	at redis.clients.jedis.util.Pool.closeInternalPool(Pool.java:122) [classes/:?]
	at redis.clients.jedis.util.Pool.destroy(Pool.java:109) [classes/:?]
	at redis.clients.jedis.tests.ShardedJedisPoolTest.returnResourceShouldResetState(ShardedJedisPoolTest.java:235) [test-classes/:?]
	... suppressed 29 lines
```

**Comment by sazzad16** [comment]
@dengliming It seems to be expected. Two of the shards have unfinished socket communication. That's why that warning is generated back-to-back twice.

Your fix is just ignoring a testing what is supposed to be tested.

However, while looking into this issue, I found the implementation of `ShardedJedisPipeline` is fundamentally unhealthy. We should consider removing this class.

**Comment by dengliming** [comment]
em.. Should we remove this class in this PR or just close it?

**Comment by dengliming** [comment]
Let's keep #2479 this issue open and close this one for now.

**Pull request closed without merging**
