### PR TITLE
Broadcast commands from UnifiedJedis

### PR DESCRIPTION
**Pull request by sazzad16**

### CODE REVIEW

**Comment by sazzad16** [comment]
@chayim @yangbodong22011 @dengliming 

Do you have like or dislike for this or #3194 ?

Here we are lengthening already huge UnifiedJedis. But it is arguably easier user experience.

**Comment by zeekling** [comment]
I think this is better.

**Comment by chayim** [comment]
> I think this is better.

@zeekling can you qualify why?

**Comment by zeekling** [comment]
> > I think this is better.
> 
> @zeekling can you qualify why?

The new code calling method has not undergone breakthrough changes and is easy to use.

**Comment by sazzad16** [comment]
Closed by #3194

**Pull request closed without merging**
