### PR TITLE
Add ZRangeParams and new zrange command

### PR DESCRIPTION
**Pull request by yangbodong22011**
This PR solves #2625, add ZRangeParams and new zrange command.

### CODE REVIEW

**Comment by yangbodong22011** [comment]
After this PR was merged, we can use `ZRangeParams` to solve #2626

**Comment by sazzad16** [comment]
@yangbodong22011 :+1: 

But I'd like to wait before deciding on this PR because I am hoping to have options like
- for zrange (by rank) -> `int star` and `int stop`
- for zrange by score -> `double min` and `double max`
- for zrange by lex -> `String min` and `String max`

**Comment by yangbodong22011** [comment]
> But I'd like to wait before deciding on this PR because I am hoping to have options like
> 
> * for zrange (by rank) -> `int star` and `int stop`
> * for zrange by score -> `double min` and `double max`
> * for zrange by lex -> `String min` and `String max`

You mean we have the following three method signatures:
```
public Set<String> zrange(final String key, final int start, final int stop, final ZRangeParams params);
public Set<String> zrangeByScore(final String key, final double min, final double max, final ZRangeParams params);
public Set<String> zrangeByLex(final String key, final String min, final String max, final ZRangeParams params);
```
And need to remove the `byscore()` and `bylex()` in `ZrangeParams`, right?

**Comment by sazzad16** [comment]
@yangbodong22011 I am not sure :(

It can be three methods or some trick in ZRangeParams. The most complicated part of thinking about it is supporting _exclusive range_ queries. Currently, Jedis does it by `zrangeByScore(String key, String min, String max)` like methods and I am not really a fan of that approach.

Let's see if others have any idea. @dengliming @mina-asham @gkorland

**Pull request closed without merging**
