### PR TITLE
(#2227) carry suppressed exceptions in the one thrown eventually

### PR DESCRIPTION
**Pull request by bigmarvin**
The proposed change would be simply putting concrete exceptions in the one thrown eventually.

As the change is simple and has little impact in functionality, and I couldn't find any unit case using this JedisSlotBasedConnectionHandler directly, I'm not adding any case against this change. Please feel free to let me know if any concern or so around this.

### CODE REVIEW

**Comment by bigmarvin** [comment]
@sazzad16, may I ask for your review and comments around this PR?

It's some simple change that brings additional info in logged stacks, which helps investigation, so I assume the feedback would be simple and straightforward. Thanks!

**Comment by sazzad16** [comment]
@bigmarvin Please check my take on this issue in #2233

**Comment by bigmarvin** [comment]
> @bigmarvin Please check my take on this issue in #2233

Thanks, so I assume the primary concern would be too many suppressed exceptions collected and logged in clusters of large scale, correct? I would have to say this is some good point, and one exception is some fair start point of investigation. Please proceed that way and I'm closing this PR.

**Comment by sazzad16** [comment]
Also, `JedisNoReachableClusterNodeException` is being created only when it's necessary.

**Pull request closed without merging**
