### PR TITLE
Automate code formatting using Maven

### PR DESCRIPTION
**Pull request by walles**
# Before this change

`CONTRIBUTING.md` encouraged reformatting sources using `make format`.

`make format` would reformat lots of files, not just the ones you changed.

# With this change in place

Any `mvn` operation will implicitly format sources.

[CI will validate code formatting](https://app.circleci.com/pipelines/github/redis/jedis/700/workflows/d76074e9-77d6-4b0c-9d9c-5508b7225fa4/jobs/850).

This implicitly means that people have to at least `mvn compile` their sources locally before making PRs to make sure they don't get refused by CI.

This enforces good practice, regardless of the actual formatting.

# Notes

Files to be reviewed (the rest have been auto formatted):
* `pom.xml`
* `Makefile`
* `.github/CONTRIBUTING.md`

Also, [checking the commits list](https://github.com/redis/jedis/pull/2494/commits) might be easier than looking at files changed, all reformatting is confined to the last change.

The code formatting Maven plugin being used didn't have any `validate` goal so I replaced with another one.

Still running the Eclipse formatter though, so `hbase-formatter.xml` still works.

`hbase-formatter.xml` is from 2014. It could potentially be replaced with [a newer one from 2019](https://github.com/apache/hbase/blob/master/dev-support/hbase_eclipse_formatter.xml), I haven't done that though.

### CODE REVIEW

**Comment by sazzad16** [comment]
@walles Would you be able to craft a separate PR with 2019 formatter? This would help us to do at least a visual comparison. Thanks either ways!

**Comment by walles** [comment]
@sazzad16 I opened #2495 as well, same thing but with the updated formatting rules.

Personally I'd go with the other one I think, but take your pick!

**Comment by sazzad16** [comment]
Thank you very much @walles

**Comment by walles** [comment]
I think having one of these PRs open should be enough. Closing in favour of #2495.

**Pull request closed without merging**
