### PR TITLE
Created example for t digest

### PR DESCRIPTION
**Pull request by Ranjeet0611**
Added Java code snippets for t-digest
 Fixes issue : #3635

### CODE REVIEW

**Comment by Ranjeet0611** [comment]
@dwdougherty please check

**Comment by dwdougherty** [comment]
Hi Ranjeet. Thank you for this. Your contribution builds in the docs and displays correctly. Unfortunately, I don't have permissions to approve and merge.

@sav-norem A Java person on your team should give it a once over.

**Comment by Ranjeet0611** [comment]
@sazzad16 could you please merge this

**Comment by sazzad16** [comment]
Closed by #3660

**Pull request closed without merging**
