### PR TITLE
Create Java code snippets for count min sketch

### PR DESCRIPTION
**Pull request by Harsh4902**
- added code snippet for CMS in Java
- Fixes: issue #3633

### CODE REVIEW

**Comment by dwdougherty** [comment]
While I didn't attempt to run the example, I did build the docs using this PR and it built and displays correctly.

**Comment by Harsh4902** [comment]
@sazzad16 please review this PR

**Review by sazzad16 — CHANGES_REQUESTED** [review]
@Harsh4902 Format it to be more readable and look nicer. Thanks

**Comment by dwdougherty** [comment]
@sazzad16 Can you be more specific? This code example seems to be consistent with the others.

**Comment by sazzad16** [comment]
@dwdougherty Please review now.

**Comment by Harsh4902** [comment]
@sazzad16 Is there any requirement of formatting now? If yes, please suggest where I can improve.

**Comment by sazzad16** [comment]
> Is there any requirement of formatting now? If yes, please suggest where I can improve.

@Harsh4902 Check my commits in this PR. I hope you would understand.

**Comment by Harsh4902** [comment]
@sazzad16 Aha, got your point. Now I will definitely take care of it. Thank you.

**Comment by dwdougherty** [comment]
@sazzad16 This PR builds correctly and it's good to go.

**Review by dwdougherty — APPROVED** [review]

**Review by sazzad16 — APPROVED** [review]

**Pull request merged**
