### PR TITLE
Add Hashes and String Example

### PR DESCRIPTION
**Pull request by bsbodden**
Hashes example  for code snippets project

### CODE REVIEW

**Comment by elena-kolevska** [comment]
@bsbodden can you please open your branch so I can send a PR?

**Comment by bsbodden** [comment]
> @bsbodden can you please open your branch so I can send a PR?
@elena-kolevska  I think it I did, as long as you have write access to Jedis I believe.

Screenshot 2023-07-11 at 10 48 41 AM

**Comment by elena-kolevska** [comment]
Thanks, I'm in! Ok, so I fixed a few small things and set the example locally; it shows up nicely.
Now back to you to make the tests pass :)

**Comment by bsbodden** [comment]
@elena-kolevska this is ready to be reviewed

**Comment by dwdougherty** [comment]
The example uses two spaces for indentation rather than four spaces, which breaks the Hugo source code highlighter. Please use multiples of four spaces throughout.

**Comment by bsbodden** [comment]
> The example uses two spaces for indentation rather than four spaces, which breaks the Hugo source code highlighter. Please use multiples of four spaces throughout.

That would make it violate Jedis indentation setting of 2. https://github.com/redis/jedis/blob/master/hbase-formatter.xml#L85

I would recommend we change Hugo's setting since most modern Java repos now use 2 spaces and it makes it visually more appealing in documentation settings.

**Comment by dwdougherty** [comment]
I'm no expert, but it looks like it's a global setting. The other languages seem to be using four spaces. I'll look into it though.

**Comment by bsbodden** [comment]
> I'm no expert, but it looks like it's a global setting. The other languages seem to be using four spaces. I'll look into it though.

Neither am I on Hugo, but I thought it used the Google Java Format, via Chroma? or something like that. But I think it eventually loads https://github.com/google/google-java-format (which I thought it was the default, and I believe it's set to 2 spaces - but this is when I was playing with Hugo like 3 year ago or so)

**Comment by dwdougherty** [comment]
In any case, apart from the appearance of the code (it's readable), the examples look fine to me. They match what's there for Python and Node.js.

I'll continue my investigation of the spacing issue.

**Comment by bsbodden** [comment]
@elena-kolevska @dwdougherty Changed the indentation to 4 spaces and added the Strings Example

**Comment by dwdougherty** [comment]
Igor was able to modify the redis-stack-website code to provide for 2-space "tabs" (didn't think he'd get to it that quickly), so you're free to use 2-space indentation. I'm sorry you changed your code before I was able to reply with a fix.

**Comment by uglide** [comment]
@bsbodden @dwdougherty LGTM

**Pull request merged**
