### PR TITLE
Support IGNORE and other optional arguments for timeseries commands

### PR DESCRIPTION
**Pull request by sazzad16**
* Re-implement TS.ADD command with optional arguments
* Implement TS.INCRBY and TS.DECRBY commands with optional arguments
* Support IGNORE argument for TS.[ CREATE | ALTER | ADD | INCRBY | DECRBY] commands

### CODE REVIEW

**Review by sazzad16 — COMMENTED** [review]
To the reviewers, I am not 100% sure about the name of `TSIncrByDecrByParams`. We usually have one Params class for one command. But in this case, two different commands (TS.INCRBY and TS.DECRBY) have exactly same set of optional arguments. Could you suggest a better class to represent optional arguments of both commands.

**Comment by atakavci** [comment]
you can try to extend from a generic base where generic type extends from base itself. And put almost everything into base and derive incrby and decrby .
like ...
```
public class TSArithmeticOpParams<T extends TSArithmeticOpParams<?>> implements IParams {

  private Long timestamp;
  private Long retentionPeriod;
  private EncodingFormat encoding;
  private Long chunkSize;
  private DuplicatePolicy duplicatePolicy;
  private Map<String, String> labels;

  public TSArithmeticOpParams() {
  }

  public T timestamp(long timestamp) {
    this.timestamp = timestamp;
    return (T) this;
  }

  @Override
  public void addParams(CommandArguments args) {
    // TODO Auto-generated method stub
    throw new UnsupportedOperationException("Unimplemented method 'addParams'");
  }
.
.
.
```

and derive like

```
public class TSDecrByParams extends TSArithmeticOpParams<TSDecrByParams> {

  public TSDecrByParams() {
  }

  public static TSDecrByParams params() {
    return new TSDecrByParams();
  }
.
.
```

**Comment by atakavci** [comment]
for future reference if you need to reuse something in a case like this;
```
public final CommandObject<Long> tsAdd(String key, long timestamp, double value, TSCreateParams createParams) { 
```
just extend a dummy **TSAdd** from **TSCreateParams** and use it. It will pay of when the time comes.

**Review by atakavci — DISMISSED** [review]
looks good, thanks

**Pull request merged**
