### PR TITLE
avoid send RST message when Socket.close() invoked

### PR DESCRIPTION
**Pull request by chimney-lee**
This setting socket.setSoLinger(true, 0)  will cause jedis client sent RST message when it receives FIN message from redis-server; which is an abortive connection release; 
Should we use an Orderly connection release here ?
https://docs.oracle.com/javase/1.5.0/docs/guide/net/articles/connection_release.html

### CODE REVIEW

**Comment by chimney-lee** [comment]
@ewhauser  @wjw465150  thanks if have look at this issue

**Comment by sazzad16** [comment]
@chimney-lee Is there any reason to close this PR?

**Comment by sazzad16** [comment]
@dengliming Do you want to reopen?

**Comment by sazzad16** [comment]
@chimney-lee Ah, thank you for the info.

**Pull request closed without merging**
