### PR TITLE
Support pipelining from UnifiedJedis

### PR DESCRIPTION
**Pull request by sazzad16**

### CODE REVIEW

**Comment by sazzad16** [comment]
Related #2767

**Review by dengliming — APPROVED** [review]

**Review by yangbodong22011 — APPROVED** [review]
LGTM，Greate Job~

**Comment by sazzad16** [comment]
@yangbodong22011 About broadcasting, do you prefer any of #3211 or #3194

**Comment by yangbodong22011** [comment]
> @yangbodong22011 About broadcasting, do you prefer any of #3211 or #3194

I will review and give my opinion as soon as possible

**Pull request merged**
