### PR TITLE
xrange make count optional

### PR DESCRIPTION
**Pull request by dengliming**
closes [https://github.com/redis/jedis/issues/2261](https://github.com/redis/jedis/issues/2261)

### CODE REVIEW

**Comment by sazzad16** [comment]
@SevereOverfl0w Does this approach fulfills yours requirement?

**Comment by sazzad16** [comment]
@dengliming It'd be helpful if you could comment on #2305. Thanks

**Comment by sazzad16** [comment]
@dengliming Do we still need this after #2305 ?

**Comment by SevereOverfl0w** [comment]
This would work, although a doc update would be helpful so it's clear this feature exists.  Additionally, having an arity which drops the count altogether would make it clear that this method is available.

**Comment by sazzad16** [comment]
@dengliming I gave a long thought and finally I have decided to prefer #2460.

**Pull request closed without merging**
