### PR TITLE
Carry first suppressed exception

### LINKED ISSUE #2227: Concrete jedis exceptions are discarded when client falls back and fails to get a random node from slot-based connection handler
### Expected behavior

When experiencing no-reachable-node-in-cluster exception from getConnection() in JedisSlotBasedConnectionHandler, I'm expecting to get concrete exceptions thrown when individual jedis instance is borrowed, if any.

### Actual behavior

These concrete exceptions are discarded, which complicates the investigation of the no-reachable-node-in-cluster exception mentioned previously. Client has to guess whether something goes wrong on the way or the expected PONG is not delivered, or so.

### Steps to reproduce:

Please create a reproducible case of your problem. Make sure
that case repeats consistently and it's not random
1. Configure contact points of cluster with some invalid/unreachable hostname
2. Try to borrow some jedis instance based on slot

### Redis / Jedis Configuration

N/A

#### Jedis version:

3.3.0

#### Redis version:

Any

#### Java version:

Any

### PR DESCRIPTION
**Pull request by sazzad16**
within JedisNoReachableClusterNodeException

Resolves #2227 
Closes #2228 
Closes #2307

### CODE REVIEW

**Comment by gkorland** [comment]
@sazzad16 why only the first exception and not all the exceptions like in https://github.com/xetorthio/jedis/pull/2228?
If we go with only the first exception why not set the exception as the cause? 

```java
edisNoReachableClusterNodeException noReachableNode = new JedisNoReachableClusterNodeException("No reachable node in cluster", superssed);
```

**Comment by sazzad16** [comment]
@gkorland This is to start a discussion about the approach. My disliking about #2228 is creating an exception (`JedisNoReachableClusterNodeException`) even when it is not necessary.

So, WDYT should be our approach? Suppressing all exception / first exception as cause / anything else?

**Comment by sazzad16** [comment]
@gkorland Please check #2228 regarding same issue.

**Comment by gkorland** [comment]
@sazzad16 what about collecting all the suppressed exceptions in a list and only in case we need to throw an exception use this list?

**Comment by sazzad16** [comment]
@gkorland WDYT about #2228 ?

**Comment by gkorland** [comment]
Yes I thought of some compromise, avoiding creating the exception in advance and still collect all the suppressed

**Review by gkorland — APPROVED** [review]

**Pull request merged**
