### PR TITLE
make socket timeout configurable for SUBSCRIBE and friends

### PR DESCRIPTION
**Pull request by 2bitoperations**
some background:
When using Amazon's hosted Redis (ElastiCache,) it's pretty common for the redis server to fail over. When it does, the former master does not always send a TCP reset or anything - frequently it just blinks offline. New connections are routed correctly to the new master, but any still-open connections wait forever for data that will never come.

This has been a pain point for us - using Jedis's .subscribe(...) functionality, our listeners will just hang forever waiting on data from the socket. We end up having to restart the JVM to get out of this bad state.

This PR attempts to add a configurable socket timeout (sotimeout) for subscribe and other long-running operations that is different from the 2-second default timeout.

The PR also attempts to nudge Jedis towards a config object + builder pattern, rather than adding an additional argument to all the (many) constructors.

(I also ran make format.)

### CODE REVIEW

**Comment by marcosnils** [comment]
@2bitoperations seems like your PR includes a lot of format changes which doesn't help to review the code. In addition, seems like tests are also not passing in CI. Can you please review and update as requested?

**Comment by 2bitoperations** [comment]
You bet - should split the "make format" change into a different pull request, or just not run the command at all?

**Comment by marcosnils** [comment]
Leave the `make format` aside, we'll apply it afterwards. Thanks for contributing, I'll review your PR whenever I have some time.

**Comment by 2bitoperations** [comment]
ok - I think I've addressed first round of concerns. left out formatting changes, and all tests pass.

**Comment by marcosnils** [comment]
@2bitoperations thx!. I'll check it out later today.

**Comment by 2bitoperations** [comment]
anxious to make progress here - is there anything I can do to help move this along?

**Comment by marcosnils** [comment]
@2bitoperations It's on my pending list to review. Hopefully will be able to take a look sometime this week.

**Comment by jhalt** [comment]
We are having the same issue and have had this issue for years. @marcosnils: Any update on this?

**Comment by jhalt** [comment]
@sazzad16: This is a major issue for pub-sub implementations. Can you please review this?

**Comment by sazzad16** [comment]
@jhalt Yes, I can review. But this PR has **BUGS**, unrelated changes, unrelated formats, separable changes, etc. So I can't approve this one.

**Comment by sazzad16** [comment]
Resolved by #2028 which is available since Jedis-3.4.0

**Pull request closed without merging**
