### PR TITLE
ROLE command implementation

### PR DESCRIPTION
**Pull request by wxisme**

### CODE REVIEW

**Comment by sazzad16** [comment]
@wxisme IMHO, it was implemented better in #1930 than this PR.

**Comment by wxisme** [comment]
@sazzad16 Ok, I didn’t see that there is already a PR. I will pay attention to it next time.

**Comment by sazzad16** [comment]
@wxisme Please feel welcome to share your view. You definitely can create a PR if you're doing it differently. I was just comparing and giving my humble opinion.

**Comment by wxisme** [comment]
@sazzad16 OK, get it.

**Review by sazzad16 — COMMENTED** [review]
@gkorland It was okay a couple of years ago. Now I'm a little bit more than `List<Object> role()`.

**Comment by sazzad16** [comment]
Resolved by #2607

**Pull request closed without merging**
