### PR TITLE
Added support for sentinel sentinels <mastername> command.

### PR DESCRIPTION
**Pull request by iousin**
This will be useful for people who would like to do low level monitoring of sentinels along with the slaves.

### CODE REVIEW

**Comment by iousin** [comment]
Hi,
Please review and approve if everything's alright. 
When I ran make format it changed bunch of files on my local machine so I didn't push these as there were no modifications to the existing files from the master. 
This feature was added in a project where redis cluster monitoring was required, including monitoring the sentinels.

**Comment by iousin** [comment]
For the test case to pass it needs a cluster of sentinels to be present. What do you think shall I modify the test case or would you like to fire up another sentinel for the test?

**Comment by iousin** [comment]
Hi, can somebody look at this please?

**Comment by HeartSaVioR** [comment]
@iousin 
I'm sorry, it took me a while to get back to this.

You can see build is failing from your modified tests.
https://travis-ci.org/xetorthio/jedis/jobs/81556140

Is recent unstable branch of Redis has bug on it? Or your code may have a bug.
You may want to investigate on it.

**Comment by iousin** [comment]
@HeartSaVioR 
Thanks for getting back. The test case needs a minimum of 2 sentinels to be up and running to pass, as sentinel sentinels command will not return data for the sentinel currently serving the request. 
If this is not an option then I'll modify the test case. 

Thanks

**Comment by marcosnils** [comment]
@HeartSaVioR, @iousin any updates about this?

**Comment by iousin** [comment]
Hi Marco, 
I have pushed in new changes which will make the test cases pass. But I think having a proper cluster test will be good by having multiple redis sentinel instances running.

**Pull request closed without merging**
