### PR TITLE
SetParams should implement equals and hashcode issue #2687

### PR DESCRIPTION
**Pull request by Lcarrot**
Add equals and hashcode in class SetParams
issue #2687

### CODE REVIEW

**Review by sazzad16 — CHANGES_REQUESTED** [review]
1. Make same change for all (or as many as possible) `...Params` classes.
2. Add unit tests.

**Comment by Lcarrot** [comment]
add equals and hashcode in Params class and add test

**Review by sazzad16 — APPROVED** [review]

**Comment by sazzad16** [comment]
Merged.
Thank you @Lcarrot for your contribution!

**Comment by JeffAtDeere** [comment]
Wow, thanks guys (I'm OP)

**Pull request merged**
