### PR TITLE
upgrade commons-pool2 to 2.7.0

### PR DESCRIPTION
**Pull request by gkorland**

### CODE REVIEW

**Comment by gkorland** [comment]
fix #2039

**Comment by sazzad16** [comment]
@gkorland Well, commons-pool2 2.7.0 doesn't support JDK 1.7! How about that?

**Comment by gkorland** [comment]
oops I missed it, in that case I'll put it on 4.0.0 milestone

**Comment by sazzad16** [comment]
@gkorland Does it mean, we are not going to support JDK 1.7 from `4.x`?

**Comment by gkorland** [comment]
I think it should be opened for discussion, what do you think?

**Comment by sazzad16** [comment]
@gkorland Check #1863

**Comment by MichalCho** [comment]
I think JDK 7 can be skipped from `4.x`. Oracle has stopped supporting it and even OpenJDK 7 goes end of support in June 2020

**Comment by sazzad16** [comment]
Closing in favor of #2165

**Pull request closed without merging**
