### PR TITLE
Fixed a grammar error to enhance readability 

### PR DESCRIPTION
**Pull request by SpotlightForBugs**
[DeepL](https://www.deepl.com/write#en/Create%20a%20branch%20with%20meaningful%20name%2C%20and%20do%20not%20modify%20the%20master%20branch%20directly.%0A)

### CODE REVIEW

**Review by sazzad16 — DISMISSED** [review]

**Comment by SpotlightForBugs** [comment]
@sazzad16 is anything I did wrong?

**Comment by sazzad16** [comment]
@SpotlightForBugs You didn't do any wrong. There are some internal reasons that makes us hesitant about merging very small non-bug-fixing pull requests. Sorry about that.

**Comment by SpotlightForBugs** [comment]
@sazzad16 
Absolutely, I can understand that

**Comment by sazzad16** [comment]
Closing as not extended enough.

**Pull request closed without merging**
