### PR TITLE
Remove WATCH from Transaction

### LINKED ISSUE #2030: ClassCastException when transaction.watch(...) is used
Jedis code expects a String return value from `transaction.watch(..)` call, while redis server doesn't return one.
This leads to "shift" in [Queuable.java](https://github.com/xetorthio/jedis/blob/jedis-3.0.1/src/main/java/redis/clients/jedis/Queable.java#L14)'s "pipelanedResponse", and then to ClassCastException (see stacktrace below), because Response<String> (crated for "watch") is used to parse Long result of "incr" call.

By "expects" I mean [MultiKeyCommandsPipeline.java](https://github.com/xetorthio/jedis/blob/jedis-3.0.1/src/main/java/redis/clients/jedis/commands/MultiKeyCommandsPipeline.java#L58) and it's implementation MultiKeyPipelineBase.java

Code:
```   
    public static void main(String[] args) {
        try (var cli = new Jedis("127.0.0.1");
            var transaction = cli.multi()) {
            transaction.watch("bar");
            transaction.incr("foo");
            transaction.exec();
        }
    }
```

### Expected behavior

Executed successfully

### Actual behavior

```
Exception in thread "main" java.lang.ClassCastException: class java.lang.Long cannot be cast to class [B (java.lang.Long and [B are in module java.base of loader 'bootstrap')
	at redis.clients.jedis.BuilderFactory$5.build(BuilderFactory.java:73)
	at redis.clients.jedis.BuilderFactory$5.build(BuilderFactory.java:70)
	at redis.clients.jedis.Response.build(Response.java:61)
	at redis.clients.jedis.Response.get(Response.java:37)
	at redis.clients.jedis.Transaction.exec(Transaction.java:53)
	at test.RedisCCE.main(RedisCCE.java:13)
```

### Steps to reproduce:

1. Start local redis instance 
2. Execute `main` code above

#### Java version: openjdk-12.0.2

### PR DESCRIPTION
**Pull request by sazzad16**
Redis doesn't support WATCH within MULTI

Resolves #2030

### CODE REVIEW

**Comment by gkorland** [comment]
@sazzad16 
LGTM! 
But I would have add a test for `pipeline.unwatch()`

**Comment by sazzad16** [comment]
@gkorland Sure thing! See https://github.com/xetorthio/jedis/pull/2032/commits/251b532cd7c5134b3fb0a30826246a3bd625eb38 in #2032 

Please consider that it's very difficult to have proper test for unwatch in pipeline mode.

**Comment by gkorland** [comment]
You can test `unwatch`  with two parallel connections or using JedisPool

**Comment by sazzad16** [comment]
@gkorland I have added tests for WATCH and UNWATCH in #2086 

https://github.com/xetorthio/jedis/blob/9de696236f59c4500f0b92c1b877d23b30e33e57/src/test/java/redis/clients/jedis/tests/PipeliningTest.java#L297-L346

so that these tests are valid for both 3.2+ and 4.0+ as this PR is for 4.0+ only.

**Comment by sazzad16** [comment]
Moved test for UNWATCH within MULTI in #2086 

https://github.com/xetorthio/jedis/blob/4a1d06b869948527a560e6a3b0eb4ca8c2a293d8/src/test/java/redis/clients/jedis/tests/commands/TransactionCommandsTest.java#L400-L414

**Review by gkorland — DISMISSED** [review]

**Comment by yangbodong22011** [comment]
LGTM

**Review by yangbodong22011 — APPROVED** [review]
LGTM

**Review by yangbodong22011 — APPROVED** [review]

**Review by dengliming — APPROVED** [review]
LGTM

**Review by gkorland — APPROVED** [review]

**Comment by sazzad16** [comment]
More references:

- #1435

**Pull request merged**
