### PR TITLE
Jedis 4

### PR DESCRIPTION
**Pull request by sazzad16**
## Description

- Changes for Jedis 4
  - Made the Connection class as the base of operations, instead of Jedis class
  - Introduced ConnectionProvider
  - Introduced CommandExecutor

- Added RedisJSON and RedisJSON 2 support

- Added RediSearch support

- Introduced JedisPooled, an easier to use JedisPool

- Introduced JedisSharding, replacing ShardedJedisPool and related classes

- Introduced ClusterPipeline and ShardedPipeline

- Introduced ReliableTransaction

### CODE REVIEW

**Comment by yangbodong22011** [comment]
Congratulations, a big change, first of all trust our unit tests.

**Comment by yangbodong22011** [comment]
We plan to no longer support ShardedJedis?

**Comment by sazzad16** [comment]
> We plan to no longer support ShardedJedis?

@yangbodong22011 That's not a priority ATM. But I hope to re-implement it with parallel paradigm of cluster mode.

**Comment by yangbodong22011** [comment]
@sazzad16 It seems that the `syncAndReturnAll` method of `Pipeline` has been removed. Is it planned or not yet supported? If it is not yet supported, I will submit a PR, including the `syncAndReturnAll` method of `ClusterPipeline` (in fact, there is already a test submission: https://github.com/yangbodong22011/jedis/commit/16a29d64b60462fd2976c1211ae8048091ca5eea)

**Comment by sazzad16** [comment]
@yangbodong22011 I just wasn't sure about the importance of it. So I have not restored it.

**Comment by yangbodong22011** [comment]
> @yangbodong22011 I just wasn't sure about the importance of it. So I have not restored it.

Such usage exists in our customers, so we need to restore it back.

**Comment by chayim** [comment]
I think we should take this opportunity to at least run the unit tests against the latest **minor** version of the included libraries. For instance junit 4.13.2 has been released since February. Let's update the poms.

It looks like code coverage decreases by 10% - so I think we should increase tests here as well, as part of merging. 

I like the way commands are now split - it'll make implementation of  missing commands much easier.

**Comment by chayim** [comment]
Some missing commands - there are others.

EXEC

- COMMAND GETKEYS
- STRALGO
- SYNC (only called on replicas)
- PSYNC (only called on replicas)

**Comment by sazzad16** [comment]
@chayim 

- EXEC
  exec() methods are part Transaction classes.
- COMMAND GETKEYS
  We have a very old issue #793 for COMMAND. No one ever asked for COMMAND GETKEYS. Probably because in our current design we already know which are the keys.
- STRALGO
  We have STRALGO.
  PS: STRALGO is **removed** (not even friendly deprecation) from Redis and so should we. https://github.com/redis/redis/commit/af7489886dab9362e4661a3015ac606025710686 
- SYNC & PSYNC (only called on replicas)
  "only called on replicas" - Jedis a client, not a replica.
  We used to have those but removed later because it didn't make sense to have those.

**Comment by sazzad16** [comment]
https://github.com/redis/jedis/pull/2693#issuecomment-976376108

> I think we should increase tests here as well

@chayim Does it mean we are now allowed to take some time for that?

**Comment by yangbodong22011** [comment]
About the `publish` command:

The current `JedisCluster` does not include `publish`, but `ClusterPipeline` does.

When testing the publish command of `ClusterPipeline`, I encountered the following npe error because `publish` does not have a `nodeKey`.
```
java.lang.NullPointerException
at redis.clients.jedis.JedisClusterInfoCache.getNodeKey(JedisClusterInfoCache.java:291)
at redis.clients.jedis.JedisClusterInfoCache.setupNodeIfNotExist(JedisClusterInfoCache.java:179)
at redis.clients.jedis.providers.ClusterConnectionProvider.getConnection(ClusterConnectionProvider.java:72)
at redis.clients.jedis.ClusterPipeline.getConnection(ClusterPipeline.java:42)
at redis.clients.jedis.MultiNodePipelineBase.appendCommand(MultiNodePipelineBase.java:36)
at redis.clients.jedis.ClusterPipeline.publish(ClusterPipeline.java:1373)
at redis.clients.jedis.tests.JedisClusterPipelineTest.pipelineWithPubSub(JedisClusterPipelineTest.java:255)
```

I recommend:
1. We need to restore the publish command in JedisCluster, we can use `channel` as key.

**Comment by sazzad16** [comment]
@yangbodong22011 current JedisCluster includes `publish`, both string and binary. Please re-check.

**Comment by yangbodong22011** [comment]
> @yangbodong22011 current JedisCluster includes `publish`, both string and binary. Please re-check.

ohh, yes, in `UnifiedJedis`, i found it, should we use `channel` as key to fix `ClusterPipeline` npe error?
```
  public final CommandObject<Long> publish(String channel, String message) {
    return new CommandObject<>(commandArguments(PUBLISH).key(channel).add(message), BuilderFactory.LONG);
  }

  public final CommandObject<Long> publish(byte[] channel, byte[] message) {
    return new CommandObject<>(commandArguments(PUBLISH).key(channel).add(message), BuilderFactory.LONG);
  }
```

**Comment by sazzad16** [comment]
@yangbodong22011 There shouldn't be any NPE. Could you please check with latest code? If the issue is there, please share your test.

**Comment by yangbodong22011** [comment]
> @yangbodong22011 There shouldn't be any NPE. Could you please check with latest code? If the issue is there, please share your test.

it's latest code in `jedis-x2`, test code is [here](https://github.com/yangbodong22011/jedis/commit/b1207679421b901d8f62b2631be629f2f4fda5cd#diff-aaa68dddd547e47e2a12f328ec801bc7bcf81535fda9db8fe3ec97f66e359741R252) .

**Comment by sazzad16** [comment]
@yangbodong22011 Could you please recheck with current code?

**Comment by yangbodong22011** [comment]
> @yangbodong22011 Could you please recheck with current code?

I have verified that it is working.  https://github.com/redis/jedis/pull/2700 all tests are passed.

**Comment by bsbodden** [comment]
A few items that I believe should be exposed to integrators using Jedis to build higher-level libraries:

* **Ability to control serialization:** Specifically for JSON but might apply to other formats. Many Frameworks including Spring, Vert.x, Micronaut and others. For example, to enable native serialization of custom classes with the `Gson` library users of Jedis should be allowed to passed their own `com.google.gson.GsonBuilder`. See https://sites.google.com/site/gson/gson-user-guide#TOC-Custom-Serialization-and-Deserialization
*  For non-JSON a concept similar to https://github.com/lettuce-io/lettuce-core/tree/main/src/main/java/io/lettuce/core/codec is needed (there might already be one, I just don't know)
* Another integration win would be to support a simple connection string scheme like  https://github.com/redis-developer/Redis-Developer-URI-Spec/blob/main/spec.md

**Review by bsbodden — APPROVED** [review]
This is great work @sazzad16 just look at my comment on the main discussion thread for my wishlist.

**Comment by sazzad16** [comment]
@bsbodden Thank you for your review + comment.

> Ability to control serialization: Specifically for JSON but might apply to other formats. Many Frameworks including Spring, Vert.x, Micronaut and others. For example, to enable native serialization of custom classes with the Gson library users of Jedis should be allowed to passed their own com.google.gson.GsonBuilder. See https://sites.google.com/site/gson/gson-user-guide#TOC-Custom-Serialization-and-Deserialization

We can definitely think about it. Which would take some time.

PS: Supporting both RedisJSON v1 and RedisJSON v2 at the same time has already made things weird (to me).

> For non-JSON a concept similar to https://github.com/lettuce-io/lettuce-core/tree/main/src/main/java/io/lettuce/core/codec is needed (there might already be one, I just don't know)

First, we would have to define how much that is needed. We may have to bring Jedis out of simplicity for this (which another discussion on it's own).

> Another integration win would be to support a simple connection string scheme like https://github.com/redis-developer/Redis-Developer-URI-Spec/blob/main/spec.md

We already have this. Check Jedis, JedisPool and (newly added) JedisPooled classes.

**Review by chayim — APPROVED** [review]

**Comment by sazzad16** [comment]
We've finally merged. Thank you @yangbodong22011, @AvitalFineRedis and @chayim.

**Comment by sazzad16** [comment]
We've finally merged the PR. Thank you @yangbodong22011, @AvitalFineRedis and @chayim.

**Comment by YNedderhoff** [comment]
Hey @sazzad16, I realise that this is just in RC state at the moment, but is there already any documentation about how to use Sharding, Pipelining, and especially pipelining with shards in version 4.0.0 so I can have a look already?

**Comment by sazzad16** [comment]
@YNedderhoff Sorry, there aren't enough documentation at this moment. We need both time and resource for that. Hopefully we'll get there.

In the mean time,

- For sharding, Jedis 4 will have JedisSharding. You can check the test files [ShardedConnectionTest](https://github.com/redis/jedis/blob/master/src/test/java/redis/clients/jedis/ShardedConnectionTest.java), [ShardingTest](https://github.com/redis/jedis/blob/master/src/test/java/redis/clients/jedis/ShardingTest.java).

  In brief, if previous code was
```
ShardedJedisPool pool = new ShardedJedisPool(...);
try (ShardedJedis jedis = pool.getResource()) {
  jedis.set(...);
}
try (ShardedJedis jedis = pool.getResource()) {
  jedis.get(...);
}
...
...
```

  Then new code would be
```
JedisSharding jedis = new JedisSharding(...);
jedis.set(...);
jedis.get(...);
...
...
```

- For pipelining in shards, there will be ShardedPipeline. There are not enough friendly constructors. But it's mostly similar of [using ClusterPipeline](https://github.com/redis/jedis/blob/master/src/test/java/redis/clients/jedis/JedisClusterPipelineTest.java).

I hope, this is helpful for you.

**Comment by YNedderhoff** [comment]
Thank you, it is! Especially pleased to see that there will be a solution for sharded pipelining, as this PR had us all worried: https://github.com/redis/jedis/issues/2488#issuecomment-847989698. Any ETA on that? We're basically stuck on 3.x until that is there in 4.x.

**Comment by sazzad16** [comment]
@YNedderhoff Jedis-4.0.0-RC1 is already out. Final release could be next week.

**Comment by YNedderhoff** [comment]
Right - thank you!

**Comment by sazzad16** [comment]
@YNedderhoff FYI, in #2731 I have renamed JedisClusterPipelineTest to [ClusterPipelineTest](https://github.com/redis/jedis/blob/master/src/test/java/redis/clients/jedis/ClusterPipelineTest.java), added [ShardedPipelineTest](https://github.com/redis/jedis/blob/master/src/test/java/redis/clients/jedis/ShardedPipelineTest.java). Also added easier constructors for related classes.

**Comment by YNedderhoff** [comment]
Thanks for the update!

**Comment by dalei2019** [comment]
Thanks for the update! + 1
Cluster pipeline is a great feature!

**Comment by dalei2019** [comment]
> @sazzad16 It seems that the `syncAndReturnAll` method of `Pipeline` has been removed. Is it planned or not yet supported? If it is not yet supported, I will submit a PR, including the `syncAndReturnAll` method of `ClusterPipeline` (in fact, there is already a test submission: [yangbodong22011@16a29d6](https://github.com/yangbodong22011/jedis/commit/16a29d64b60462fd2976c1211ae8048091ca5eea))

syncAndReturnAll is useful ！

**Comment by yangbodong22011** [comment]
> > @sazzad16 It seems that the `syncAndReturnAll` method of `Pipeline` has been removed. Is it planned or not yet supported? If it is not yet supported, I will submit a PR, including the `syncAndReturnAll` method of `ClusterPipeline` (in fact, there is already a test submission: [yangbodong22011@16a29d6](https://github.com/yangbodong22011/jedis/commit/16a29d64b60462fd2976c1211ae8048091ca5eea))
> 
> syncAndReturnAll is useful ！

@dalei2019 Do you want the `syncAndReturnAll` method of `ClusterPipeline.class`? (Note: `Pipeline.class` has been restore `syncAndReturnAll`)

**Comment by dalei2019** [comment]
> syncAndReturnAll

Yes！It's very useful! 
 I look forward to using the pipeline function in cluster mode, just like single instance mode.

**Comment by sazzad16** [comment]
@dalei2019 Simply maintain a `List<Response>` and your code is same for both Pipeline and ClusterPipeline.

```
    List<Response> responses = new ArrayList<>();

    responses.add(pipeline.command(...));
    responses.add(pipeline.command(...));
    responses.add(pipeline.command(...));

    pipeline.sync();

    for (Response res : responses) {
      res.get();
    }
```

**Comment by MSPigl** [comment]
@sazzad16 Maybe this is the wrong place for this, however I'm seeing removals of functionality without documentation on replacement. I'm currently upgrading my team's codebase to Jedis 4. Currently, we're leveraging `jedis.getClient()`, and then using `getHost()` and `getPort()` from the returned object. I see that on Jedis 4, `getClient()` is just a passthrough to `getConnection()`, and I'm not seeing a way to get the host and port from a `Jedis` instance now. How would you recommend I get that data?

**Comment by sazzad16** [comment]
@MSPigl Only now that you have mentioned, we have just realized that `getHost()` and `getPort()` were not deprecated in Jedis 3.x. These were removed because these were related to `setHost()` and `setPort()` which were decided to be removed and deprecated.

Could you please describe you usage of `getHost()` and `getPort()`?
BTW, please continue this discussion in a new [Discussion](https://github.com/redis/jedis/discussions).
Thanks

**Pull request merged**
