### PR TITLE
Deploy SNAPSHOTs to Sonatype's OSS Snapshot Repo.

### PR DESCRIPTION
**Pull request by mp911de**
TravisCI now deploys jedis SNAPSHOT artifacts to Sonatype's OSS Snapshot Repo if:
- The build is not a pull-request
- Travis has secure env variables set up
- The artifact version ends with SNAPSHOT

---

Related ticket: #1369 
Requires secure env variables to be set up in [TravisCI](https://travis-ci.org/xetorthio/jedis/settings), specifically:
- `CI_DEPLOY_USERNAME`
- `CI_DEPLOY_PASSWORD`

### CODE REVIEW

**Comment by marcosnils** [comment]
@mp911de this is amazing. We'll try it today and hopefully merge!.

**Comment by HeartSaVioR** [comment]
Amazing work @mp911de.
I guess this requires Jonathan's key or credentials, so would like to wait him for that.

**Comment by mp911de** [comment]
You can run that from a branch to make sure it works before merging into master.

**Comment by marcosnils** [comment]
@gkorland Now that you have access to sonatype, we can push this to get SNAPSHOT releases.

**Comment by sazzad16** [comment]
It has been sometime that the snapshots are being published.

E.g. at this moment

```
  <repositories>
    <repository>
      <id>snapshots-repo</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
    </repository>
  </repositories>
```
and
```
  <dependencies>
    <dependency>
      <groupId>redis.clients</groupId>
      <artifactId>jedis</artifactId>
      <version>3.5.0-SNAPSHOT</version>
    </dependency>
  </dependencies>
```

**Pull request closed without merging**
