### PR TITLE
Java example code snippets for T-Digest and TopK

### PR DESCRIPTION
**Pull request by Ranjeet0611**
Added Java code snippets for topk
Fixes issue : #3634

### CODE REVIEW

**Comment by Ranjeet0611** [comment]
@dwdougherty please check this one also Thank you

**Comment by dwdougherty** [comment]
Hi Ranjeet. Thanks again for your contribution. Much appreciated.

The example builds correctly, so I approve. As I said previously, I don't have permission to approve formally and merge, so a maintainer will have to do so.

**Review by dwdougherty — APPROVED** [review]
LGTM

**Comment by Ranjeet0611** [comment]
@dwdougherty  whom should i tag for merging this pr?

**Pull request merged**
