### PR TITLE
add crc32hash and compatible with RedisShardAPI

### PR DESCRIPTION
**Pull request by SeaSand1024**
When we use RedisShardAPI in python with crc32hash, we can't compatible with Jedis,In addition, we will also add sharding algorithms,because it is different from python.

### CODE REVIEW

**Comment by sazzad16** [comment]
@SeaSand1024 Have you checked if this implementation is actually compatible with RedisShardAPI?

**Comment by SeaSand1024** [comment]
> @SeaSand1024 Have you checked if this implementation is actually compatible with RedisShardAPI?
Yes, I did. You'd better specify the format of HostAndPort the same as python if you use ShardedConnectionProvider.The default format is "host:port".

**Comment by SeaSand1024** [comment]
> @SeaSand1024 Have you checked if this implementation is actually compatible with RedisShardAPI?



> @SeaSand1024 Have you checked if this implementation is actually compatible with RedisShardAPI?

Have you checked if this implementation is actually compatible with RedisShardAPI?

**Comment by SeaSand1024** [comment]
> @SeaSand1024 Have you checked if this implementation is actually compatible with RedisShardAPI?

Yes, I did. You'd better specify the format of HostAndPort the same as python if you use ShardedConnectionProvider.The default format is "host:port".

**Comment by sazzad16** [comment]
Sharding feature will be removed.

**Pull request closed without merging**
